version: '3.8'

services:
  # Main application
  namaste-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namaste-sync-app
    expose:
      - "80"
      - "3000"
    volumes:
      - mongodb_data:/data/db
      - app_logs:/var/log
    environment:
      - NODE_ENV=production
      - VITE_MONGODB_URI=mongodb://localhost:27017/namaste-sync
      - VITE_MONGODB_DB_NAME=namaste-sync
      - VITE_APP_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - namaste-network
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  # Reverse proxy for remote access
  nginx-proxy:
    image: nginx:alpine
    container_name: namaste-sync-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - proxy_logs:/var/log/nginx
    depends_on:
      - namaste-sync
    restart: unless-stopped
    networks:
      - namaste-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # MongoDB for external access (optional)
  mongodb:
    image: mongo:6.0
    container_name: namaste-sync-mongo-external
    ports:
      - "27018:27017"  # Different port to avoid conflict
    volumes:
      - mongodb_external_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=SecurePassword123!
      - MONGO_INITDB_DATABASE=namaste-sync
    restart: unless-stopped
    networks:
      - namaste-network
    command: mongod --auth
    
  # MongoDB monitoring (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: namaste-sync-mongo-ui
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=SecurePassword123!
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - namaste-network
    profiles:
      - monitoring

  # Application monitoring
  portainer:
    image: portainer/portainer-ce:latest
    container_name: namaste-sync-portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - namaste-network
    profiles:
      - monitoring

volumes:
  mongodb_data:
    driver: local
  mongodb_external_data:
    driver: local
  app_logs:
    driver: local
  proxy_logs:
    driver: local
  portainer_data:
    driver: local

networks:
  namaste-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16